Check for linkinfo before iterating
- If we don't check for this, when running **get_linked_docs** on Document that doesn't have the meta **("__linked_with")** then it will return error since linkinfo is None
- For example:
``` python
# This line will return error regardless of Document Name passed:
frappe.widgets.form.utils.get_linked_docs("Salary Structure", "TESTEMP001/SST/00001", no_metadata=True)
# for dt, link in linkinfo.items():
# AttributeError: 'NoneType' object has no attribute 'items'
```