fix: Error when running "build-message-files"
I get the following error when running "bench build-message-files":

File "/Users/__________/frappe-gmuni/apps/frappe/frappe/translate.py", line 578, in write_csv_file
w.writerow([p.encode('utf-8') if p else '', m.encode('utf-8'), t.encode('utf-8')])
TypeError: a bytes-like object is required, not 'str'