fix: 'TopBarItem' object does not support item assignment #17926
TypeError: 'TopBarItem' object does not support item assignment
(cherry picked from commit 9358655ae2d251218586b5ae32dafde6441b6e96)