fix(list_view): fix crash when `$result` is undefined
```
TypeError: Cannot read properties of undefined (reading 'find')
  at frappe.views.ListViewget_count_element(../../../../../apps/frappe/frappe/public/js/frappe/list/list_view.js:643:23)
  at frappe.views.ListViewfreeze(../../../../../apps/frappe/frappe/public/js/frappe/list/list_view.js:500:9)
  at frappe.views.BaseListrefresh(../../../../../apps/frappe/frappe/public/js/frappe/list/base_list.js:524:8)
  at frappe.views.ListViewrefresh(../../../../../apps/frappe/frappe/public/js/frappe/list/list_view.js:306:16)
  at frappe.views.ListView.refresh(../../../../../apps/frappe/frappe/public/js/frappe/utils/utils.js:879:19)
  at <anonymous>(../../../../../apps/frappe/frappe/public/js/frappe/list/list_view.js:253:10)
  at sentryWrapped(../../../../../apps/frappe/node_modules/src/helpers.ts:98:1)
```

Sentry support: 22590

Signed-off-by: Akhil Narang <me@akhilnarang.dev>
(cherry picked from commit 0393faf375ce8e4d73d2c912c76b5bd1e743d174)