fix(query_report): sentry FRAPPE-2TF
```
TypeError: Cannot read properties of undefined (reading 'map')
  at items.action(../../../../../apps/frappe/frappe/public/js/frappe/views/reports/query_report.js:1688:39)
  at $link(../../../../../apps/frappe/frappe/public/js/frappe/ui/page.js:506:11)
  at jQuery.event.dispatch(../../../../../apps/frappe/node_modules/jquery/dist/jquery.js:5135:27)
  at elemData.handle(../../../../../apps/frappe/node_modules/jquery/dist/jquery.js:4939:28)
  at sentryWrapped(../../../../../apps/frappe/node_modules/src/helpers.ts:98:1)
```

Signed-off-by: Akhil Narang <me@akhilnarang.dev>
(cherry picked from commit eb509e9ae8431669ededd624f5bca6a583c91cfd)