Update base_document.py
As explained in the issue "https://github.com/frappe/frappe/issues/28039" there is the need to apply a double control to the variable "df" at line 1157, so to avoid "AttributeError: 'NoneType' object has no attribute 'fieldtype'"