chore(deps): bump gitpython from 2.1.11 to 2.1.15 (#9619)
* chore(deps): bump gitpython from 2.1.11 to 2.1.15

Bumps [gitpython](https://github.com/gitpython-developers/GitPython) from 2.1.11 to 2.1.15.
- [Release notes](https://github.com/gitpython-developers/GitPython/releases)
- [Changelog](https://github.com/gitpython-developers/GitPython/blob/master/CHANGES)
- [Commits](https://github.com/gitpython-developers/GitPython/compare/2.1.11...2.1.15)

Signed-off-by: dependabot-preview[bot] <support@dependabot.com>

Signed-off-by: Chinmay D. Pai <chinmaydpai@gmail.com>

* chore: pin braintree to 3.59.0

braintree dropped python3 support with 4.0.0, so for python2 we need to
pin it to 3.59.0

Signed-off-by: Chinmay D. Pai <chinmaydpai@gmail.com>

* chore: pin braintree only for python < 3.6

Signed-off-by: Chinmay D. Pai <chinmaydpai@gmail.com>

* chore: pin xmlrunner to 2.5.2

python2 support was dropped with the newer xmlrunner release, so right
now tests fail with the following error:

Traceback (most recent call last):

  File "/opt/python/2.7.14/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/python/2.7.14/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/travis/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/travis/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/travis/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/travis/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/frappe-bench/env/lib/python2.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/travis/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/travis/frappe-bench/apps/frappe/frappe/commands/utils.py", line 402, in run_tests
    import frappe.test_runner
  File "/home/travis/frappe-bench/apps/frappe/frappe/test_runner.py", line 8, in <module>
    import xmlrunner
  File "/home/travis/frappe-bench/env/lib/python2.7/site-packages/xmlrunner/__init__.py", line 11, in <module>
    from .runner import XMLTestRunner
  File "/home/travis/frappe-bench/env/lib/python2.7/site-packages/xmlrunner/runner.py", line 7, in <module>
    from .result import _XMLTestResult
  File "/home/travis/frappe-bench/env/lib/python2.7/site-packages/xmlrunner/result.py", line 42, in <module>
    for (low, high) in _illegal_unichrs
ValueError: chr() arg not in range(256)

Signed-off-by: Chinmay D. Pai <chinmaydpai@gmail.com>

* chore: remove python version marker for xmlrunner

Signed-off-by: Chinmay D. Pai <chinmaydpai@gmail.com>

* chore: add missing = in environment marker

Signed-off-by: Chinmay D. Pai <chinmaydpai@gmail.com>