fix(print_utils): simplify checks
Make it more readable, and prevent error

Sentry FRAPPE-4SQ

```
TypeError: Cannot read properties of undefined (reading 'default_letter_head')
  at frappe.ui.get_print_settings(../../../../../apps/frappe/frappe/public/js/frappe/form/print_utils.js:6:65)
  at items.action(../../../../../apps/frappe/frappe/public/js/frappe/views/reports/query_report.js:1640:29)
  at $link(../../../../../apps/frappe/frappe/public/js/frappe/ui/page.js:506:11)
  at jQuery.event.dispatch(../../../../../apps/frappe/node_modules/jquery/dist/jquery.js:5135:27)
  at elemData.handle(../../../../../apps/frappe/node_modules/jquery/dist/jquery.js:4939:28)
  at sentryWrapped(../../../../../apps/frappe/node_modules/src/helpers.ts:98:1)```

Signed-off-by: Akhil Narang <me@akhilnarang.dev>
(cherry picked from commit cfc8d7a010a4b678be40714ca8cb7c4071f36a2a)