fix(query_report): fix crash
```
TypeError: i.get_value is not a function. (In 'i.get_value()', 'i.get_value' is undefined)
  at <anonymous>(../../../../../apps/frappe/frappe/public/js/frappe/views/reports/query_report.js:1332:21)
  at filter([native code])
  at frappe.views.QueryReportget_filter_values(../../../../../apps/frappe/frappe/public/js/frappe/views/reports/query_report.js:1332:5)
  at erpnext.financial_statementsonload(../../../../../apps/erpnext/erpnext/public/js/financial_statements.js:119:24)
  at ChartWidget.setup_filter_dialog(../../../../../apps/frappe/frappe/public/js/frappe/widgets/chart_widget.js:415:54)
  at <anonymous>(../../../../../apps/frappe/frappe/public/js/frappe/widgets/chart_widget.js:386:12)
```

Sentry support: 22569

Signed-off-by: Akhil Narang <me@akhilnarang.dev>
(cherry picked from commit 1ad41131677eb0df70d11eb96b4410d1ba966d54)