fix(requirements): remove psycopg2 from requirements
apparently, since version 2.8, psycopg2 does not install the
binary version by default (read source), and hence fails on setup
with the error:

Error: pg_config executable not found

since nobody can really be arsed to compile this binary on their
own, we'll stick to using psycopg2-binary instead.

source: [pgsql mailing list](https://www.postgresql.org/message-id/CA%2Bmi_8bd6kJHLTGkuyHSnqcgDrJ1uHgQWvXCKQFD3tPQBUa2Bw%40mail.gmail.com).

Signed-off-by: Chinmay D. Pai <chinmaydpai@gmail.com>