fix(grid_row): don't crash when undefined
TypeError: Cannot read properties of undefined (reading 'fields')
  at frappe.ui.form.ControlTable.get_field(../../../../../apps/frappe/frappe/public/js/frappe/form/controls/table.js:120:18)
  at HTMLInputElement.<anonymous>(../../../../../apps/frappe/frappe/public/js/frappe/form/controls/table.js:46:13)
  at jQuery.event.dispatch(../../../../../apps/frappe/node_modules/jquery/dist/jquery.js:5135:27)
  at elemData.handle(../../../../../apps/frappe/node_modules/jquery/dist/jquery.js:4939:28)
  at sentryWrapped(../../../../../apps/frappe/node_modules/src/helpers.ts:98:1)

Sentry FRAPPE-698

Signed-off-by: Akhil Narang <me@akhilnarang.dev>
(cherry picked from commit 0892609710908a4fc353d4226e5af40d90656bc2)