fix: Check if header/footer html exists before trying to extract
- issue: AttributeError: 'NoneType' object has no attribute 'extract', when no letterhead html was present

(cherry picked from commit 4d2c4f020bac93bdd648c4d3c1f514891c41d908)