fix(Event Streaming): Doctype dependencies sync (#14299)
File "/home/mai/Workspace/V13/v13_online/apps/frappe/frappe/event_streaming/doctype/event_producer/event_producer.py", line 414, in sync_child_table_dependencies
    child_doc = frappe._dict(child_doc)
TypeError: 'NoneType' object is not iterable

(cherry picked from commit 1534e5398af4a8971c754fac2c65f87bb8b898a5)