fix: test case for time input
Cypress refuses to type "wrong" data into time input fields:

CypressError: Typing into a `time` input with `cy.type()` requires a valid time with the format `HH:mm`, `HH:mm:ss` or `HH:mm:ss.SSS`, where `HH` is 00-23, `mm` is 00-59, `ss` is 00-59, and `SSS` is 000-999. You passed: `  11:00:12`.

I think we can rely on the browser for the field to work.