fix: Bail if no SMTP acccount can be found
Currently we give this weird error instead of just saying no outgoing email account is configured.

```
AttributeError: 'NoneType' object has no attribute 'get_smtp_server'
  File "frappe/email/queue.py", line 154, in flush
    email_queue.send()
  File "frappe/email/doctype/email_queue/email_queue.py", line 160, in send
    with SendMailContext(self, smtp_server_instance) as ctx:
  File "frappe/email/doctype/email_queue/email_queue.py", line 236, in __init__
    self.smtp_server: SMTPServer = smtp_server_instance or self.email_account_doc.get_smtp_server()
```

(cherry picked from commit 78665d98b2d4a4cff3577854741d69d244c4b6f9)