bug: manually calling the add function in frappe.desk.form.assign_to for doctype with Auto Name set to autoincrement as naming series gives error
Manually calling the add function in frappe.desk.form.assign_to for doctype with Auto Name set to autoincrement as naming series gives the error -> AttributeError: 'int' object has no attribute 'doctype'
The error arises due to doc.name being taken as an int instead of string while calling the frappe.share.add(doc.doctype, doc.name, assign_to) function inside the frappe.desk.form.assign_to.add function.